'use strict';
const NAMESPACES = {
    HTML: 'http://www.w3.org/1999/xhtml',
    MATHML: 'http://www.w3.org/1998/Math/MathML',
    SVG: 'http://www.w3.org/2000/svg',
    XLINK: 'http://www.w3.org/1999/xlink',
    XML: 'http://www.w3.org/XML/1998/namespace',
    XMLNS: 'http://www.w3.org/2000/xmlns/'
};

const TAG_NAMES = {
    A: 'a',
    ADDRESS: 'address',
    ANNOTATION_XML: 'annotation-xml',
    APPLET: 'applet',
    AREA: 'area',
    ARTICLE: 'article',
    ASIDE: 'aside',

    B: 'b',
    BASE: 'base',
    BASEFONT: 'basefont',
    BGSOUND: 'bgsound',
    BIG: 'big',
    BLOCKQUOTE: 'blockquote',
    BODY: 'body',
    BR: 'br',
    BUTTON: 'button',

    CAPTION: 'caption',
    CENTER: 'center',
    CODE: 'code',
    COL: 'col',
    COLGROUP: 'colgroup',

    DD: 'dd',
    DESC: 'desc',
    DETAILS: 'details',
    DIALOG: 'dialog',
    DIR: 'dir',
    DIV: 'div',
    DL: 'dl',
    DT: 'dt',

    EM: 'em',
    EMBED: 'embed',

    FIELDSET: 'fieldset',
    FIGCAPTION: 'figcaption',
    FIGURE: 'figure',
    FONT: 'font',
    FOOTER: 'footer',
    FOREIGN_OBJECT: 'foreignObject',
    FORM: 'form',
    FRAME: 'frame',
    FRAMESET: 'frameset',

    H1: 'h1',
    H2: 'h2',
    H3: 'h3',
    H4: 'h4',
    H5: 'h5',
    H6: 'h6',
    HEAD: 'head',
    HEADER: 'header',
    HGROUP: 'hgroup',
    HR: 'hr',
    HTML: 'html',

    I: 'i',
    IMG: 'img',
    IMAGE: 'image',
    INPUT: 'input',
    IFRAME: 'iframe',

    KEYGEN: 'keygen',

    LABEL: 'label',
    LI: 'li',
    LINK: 'link',
    LISTING: 'listing',

    MAIN: 'main',
    MALIGNMARK: 'malignmark',
    MARQUEE: 'marquee',
    MATH: 'math',
    MENU: 'menu',
    META: 'meta',
    MGLYPH: 'mglyph',
    MI: 'mi',
    MO: 'mo',
    MN: 'mn',
    MS: 'ms',
    MTEXT: 'mtext',

    NAV: 'nav',
    NOBR: 'nobr',
    NOFRAMES: 'noframes',
    NOEMBED: 'noembed',
    NOSCRIPT: 'noscript',

    OBJECT: 'object',
    OL: 'ol',
    OPTGROUP: 'optgroup',
    OPTION: 'option',

    P: 'p',
    PARAM: 'param',
    PLAINTEXT: 'plaintext',
    PRE: 'pre',

    RB: 'rb',
    RP: 'rp',
    RT: 'rt',
    RTC: 'rtc',
    RUBY: 'ruby',

    S: 's',
    SCRIPT: 'script',
    SECTION: 'section',
    SELECT: 'select',
    SOURCE: 'source',
    SMALL: 'small',
    SPAN: 'span',
    STRIKE: 'strike',
    STRONG: 'strong',
    STYLE: 'style',
    SUB: 'sub',
    SUMMARY: 'summary',
    SUP: 'sup',

    TABLE: 'table',
    TBODY: 'tbody',
    TEMPLATE: 'template',
    TEXTAREA: 'textarea',
    TFOOT: 'tfoot',
    TD: 'td',
    TH: 'th',
    THEAD: 'thead',
    TITLE: 'title',
    TR: 'tr',
    TRACK: 'track',
    TT: 'tt',

    U: 'u',
    UL: 'ul',

    SVG: 'svg',

    VAR: 'var',

    WBR: 'wbr',

    XMP: 'xmp'
}

const HTML = { 
    NAMESPACES, 
    TAG_NAMES,
    ATTRS: {
        TYPE: 'type',
        ACTION: 'action',
        ENCODING: 'encoding',
        PROMPT: 'prompt',
        NAME: 'name',
        COLOR: 'color',
        FACE: 'face',
        SIZE: 'size'
    },
    DOCUMENT_MODE: {
        NO_QUIRKS: 'no-quirks',
        QUIRKS: 'quirks',
        LIMITED_QUIRKS: 'limited-quirks'
    },
    SPECIAL_ELEMENTS: {
        [NAMESPACES.HTML]: {
            [TAG_NAMES.ADDRESS]: true,
            [TAG_NAMES.APPLET]: true,
            [TAG_NAMES.AREA]: true,
            [TAG_NAMES.ARTICLE]: true,
            [TAG_NAMES.ASIDE]: true,
            [TAG_NAMES.BASE]: true,
            [TAG_NAMES.BASEFONT]: true,
            [TAG_NAMES.BGSOUND]: true,
            [TAG_NAMES.BLOCKQUOTE]: true,
            [TAG_NAMES.BODY]: true,
            [TAG_NAMES.BR]: true,
            [TAG_NAMES.BUTTON]: true,
            [TAG_NAMES.CAPTION]: true,
            [TAG_NAMES.CENTER]: true,
            [TAG_NAMES.COL]: true,
            [TAG_NAMES.COLGROUP]: true,
            [TAG_NAMES.DD]: true,
            [TAG_NAMES.DETAILS]: true,
            [TAG_NAMES.DIR]: true,
            [TAG_NAMES.DIV]: true,
            [TAG_NAMES.DL]: true,
            [TAG_NAMES.DT]: true,
            [TAG_NAMES.EMBED]: true,
            [TAG_NAMES.FIELDSET]: true,
            [TAG_NAMES.FIGCAPTION]: true,
            [TAG_NAMES.FIGURE]: true,
            [TAG_NAMES.FOOTER]: true,
            [TAG_NAMES.FORM]: true,
            [TAG_NAMES.FRAME]: true,
            [TAG_NAMES.FRAMESET]: true,
            [TAG_NAMES.H1]: true,
            [TAG_NAMES.H2]: true,
            [TAG_NAMES.H3]: true,
            [TAG_NAMES.H4]: true,
            [TAG_NAMES.H5]: true,
            [TAG_NAMES.H6]: true,
            [TAG_NAMES.HEAD]: true,
            [TAG_NAMES.HEADER]: true,
            [TAG_NAMES.HGROUP]: true,
            [TAG_NAMES.HR]: true,
            [TAG_NAMES.HTML]: true,
            [TAG_NAMES.IFRAME]: true,
            [TAG_NAMES.IMG]: true,
            [TAG_NAMES.INPUT]: true,
            [TAG_NAMES.LI]: true,
            [TAG_NAMES.LINK]: true,
            [TAG_NAMES.LISTING]: true,
            [TAG_NAMES.MAIN]: true,
            [TAG_NAMES.MARQUEE]: true,
            [TAG_NAMES.MENU]: true,
            [TAG_NAMES.META]: true,
            [TAG_NAMES.NAV]: true,
            [TAG_NAMES.NOEMBED]: true,
            [TAG_NAMES.NOFRAMES]: true,
            [TAG_NAMES.NOSCRIPT]: true,
            [TAG_NAMES.OBJECT]: true,
            [TAG_NAMES.OL]: true,
            [TAG_NAMES.P]: true,
            [TAG_NAMES.PARAM]: true,
            [TAG_NAMES.PLAINTEXT]: true,
            [TAG_NAMES.PRE]: true,
            [TAG_NAMES.SCRIPT]: true,
            [TAG_NAMES.SECTION]: true,
            [TAG_NAMES.SELECT]: true,
            [TAG_NAMES.SOURCE]: true,
            [TAG_NAMES.STYLE]: true,
            [TAG_NAMES.SUMMARY]: true,
            [TAG_NAMES.TABLE]: true,
            [TAG_NAMES.TBODY]: true,
            [TAG_NAMES.TD]: true,
            [TAG_NAMES.TEMPLATE]: true,
            [TAG_NAMES.TEXTAREA]: true,
            [TAG_NAMES.TFOOT]: true,
            [TAG_NAMES.TH]: true,
            [TAG_NAMES.THEAD]: true,
            [TAG_NAMES.TITLE]: true,
            [TAG_NAMES.TR]: true,
            [TAG_NAMES.TRACK]: true,
            [TAG_NAMES.UL]: true,
            [TAG_NAMES.WBR]: true,
            [TAG_NAMES.XMP]: true
        },
        [NAMESPACES.MATHML]: {
            [TAG_NAMES.MI]: true,
            [TAG_NAMES.MO]: true,
            [TAG_NAMES.MN]: true,
            [TAG_NAMES.MS]: true,
            [TAG_NAMES.MTEXT]: true,
            [TAG_NAMES.ANNOTATION_XML]: true
        },
        [NAMESPACES.SVG]: {
            [TAG_NAMES.TITLE]: true,
            [TAG_NAMES.FOREIGN_OBJECT]: true,
            [TAG_NAMES.DESC]: true
        }
    }
 };

 module.exports = HTML;